systemLog:
  destination: file
  path: "/usr/local/services/mongodb/log/mongodbsystem.log"
  logAppend: true
storage:
  journal:
    enabled: true
  dbPath: "/data/mongodbdata"
  engine: wiredTiger
  wiredTiger:
      engineConfig:
         cacheSizeGB: 8
         journalCompressor: zlib
         directoryForIndexes: false
      collectionConfig:
         blockCompressor: zlib
      indexConfig:
         prefixCompression: true
processManagement:
  fork: true
net:
  bindIp: 192.168.1.204
  port: 21000
setParameter:
  enableLocalhostAuthBypass: false
  authenticationMechanisms: SCRAM-SHA-1 
security:
  keyFile: "/usr/local/services/mongodb/mongodb.key"
# clusterAuthMode: "keyFile"
  authorization: "enabled"
#sharding:
#  iclusterRole: configsvr
replication:
  replSetName: cfgReplSet
  oplogSizeMB: 2048 
  secondaryIndexPrefetch: all
  enableMajorityReadConcern: true
